### ISSUE TITLE
Why log 1000 info statements in a single request?

### ISSUE THREAD

**Issue by wsargent** [sdaschner/quarkus-logging-comparison#2]
Even in the most verbose production environments -- the honeycomb event model -- the recommendation is to capture all the relevant information in a request and write that out as a broad "high cardinality" log statement at the completion of the request -- that would be one info statement per request.

Even in a debugging circumstance, I'd consider 1000 statements in a request to be very high.  What's the reasoning behind this?

**Comment by sdaschner** [comment]
Yes indeed, this a constructed example, however I've seen real-world apps that logged _a lot_ per single business use case, which indeed was the inspiration to write up these blog posts after a specific recent project.

The reasoning was to show the performance impact writing text-based logging statements has on our application. For that, and to compare different approaches, I wanted a high pressure on the logging impl hence that many statements.
