### ISSUE TITLE
Please include JVM version and settings

### ISSUE THREAD

**Issue by wsargent** [sdaschner/quarkus-logging-comparison#3]
In https://blog.sebastian-daschner.com/entries/logging-performance-comparison you mention the hardware, but not what JVM version you're running under -- the JVM version and GC configuration can have a significant impact on IO and on garbage collection performance, so it's relevant.

**Comment by sdaschner** [comment]
Good point, thanks, updated :)
I'm using OpenJDK 18.0.1 (build 18.0.1+10)
